version: '3'
services:
  harvest-app:
    image: harvest-app
  api:
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile
    image: harvest-api
    volumes:
      - ../api:/app
      - /app/node_modules
    ports:
      - '8080'
